session_name: "config"
windows:
  - window_name: todo
    start_directory: ~/zettelkasten
    panes:
      - shell_command: nvim todo.md
  - window_name: zsh
    start_directory: ~/
    panes:
      - shell_command: nvim .zshrc .aliases
  - window_name: scripts
    start_directory: ~/dotfiles/config/bin
    panes:
      - shell_command: nvim .
  - window_name: sway
    start_directory: ~/dotfiles/config/sway
    panes:
      - shell_command: nvim .
