session_name: "Cheatsheet/Notes"
start_directory: ${NOTES_PATH}
windows:
  - window_name: latexmk
    layout: main-vertical
    panes:
      - shell_command: '[ -f output/main.pdf ] &&  zathura output/main.pdf'
      - shell_command: latexmk -pdf -outdir=output -pvc --shell-escape main.tex
  - window_name: editor
    focus: true
    panes:
      - shell_command: nvim .
