session_name: "${SUBJECT_NAME}"
windows:
  - window_name: editor zettelkasten
    start_directory: "~/zettelkasten"
    focus: true
    panes:
      - shell_command: "nvim ."
  - window_name: resources
    start_directory: "${SUBJECT_PATH}"
    panes:
      - shell_command: "[ -f ./.tmuxp_script.sh ] && ./.tmuxp_script.sh"
  - window_name: latex compiler output
    start_directory: "${SUBJECT_PATH}/summary"
    layout: main-vertical
    panes:
      - shell_command: '[ -f output/main.pdf ] &&  zathura output/main.pdf &'
      - shell_command: latexmk -pdf -outdir=output -pvc --shell-escape main.tex
  - window_name: editor summary 
    start_directory: "${SUBJECT_PATH}/summary"
    panes:
      - shell_command: nvim main.tex
